Repository Swyp-team10/molip-front, pull requests merged in 2024-07, with the labels that each got.

#10 feat:Default Button
  src/app/_component/button/Button.tsx
  src/app/_component/button/button.module.css
  src/app/page.tsx
  src/app/styles/globals.css
  src/app/styles/page.module.css
Labels: STYLE, 이수현

#14 Style/splash
  public/logo/Logo_noBg_white.svg
  src/app/components/Splash.tsx
  src/app/components/spalsh.module.css
  src/app/page.tsx
Labels: STYLE, 이수현

#16 Style: 메뉴 카드 모달 컴포넌트 작업 완
  package-lock.json
  package.json
  public/image/감자탕.jpg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/RQProvider.tsx
  src/components/buttons/Button.tsx
  src/components/buttons/button.module.css
  src/components/modals/MenuCardModal.tsx
  src/components/modals/menuCardModal.module.css
Labels: STYLE, 정재호

#18 Style/round option button
  public/icons/buttons/check.svg
  public/icons/buttons/option.svg
  src/app/components/RQProvider.tsx
  src/app/components/buttons/Button.tsx
  src/app/components/buttons/button.module.css
  src/app/page.tsx
  src/components/Splash.tsx
  src/components/buttons/RoundButton.tsx
  src/components/buttons/ShareButton.tsx
  src/components/buttons/roundButton.module.css
  src/components/buttons/share.module.css
  src/components/spalsh.module.css
Labels: STYLE, 이수현

#20 Style/top menu button
  src/app/page.tsx
  src/components/buttons/TopMenuButton.tsx
  src/components/buttons/topMenuButton.module.css
Labels: STYLE, 이수현

#21 Style: 체험판 모달 컴포넌트 작업 및 모달에 들어가는 버튼 컴포넌트 작업 완료
  src/app/page.tsx
  src/components/buttons/ModalButton.tsx
  src/components/buttons/modalButton.module.css
  src/components/modals/MenuCardModal.tsx
  src/components/modals/TrialViewModal.tsx
  src/components/modals/menuCardModal.module.css
  src/components/modals/trialViewModal.module.css
Labels: STYLE, 정재호

#25 Fix/top menu button
  public/logo/Logo_noBg_orange.svg
  src/app/page.tsx
  src/app/styles/globals.css
  src/app/styles/variables.css
  src/components/buttons/Button.tsx
  src/components/buttons/ModalButton.tsx
  src/components/buttons/OptionButton.tsx
  src/components/buttons/RoundButton.tsx
  src/components/buttons/ShareButton.tsx
  src/components/buttons/TopMenuButton.tsx
  src/components/buttons/styles/button.module.css
  src/components/buttons/styles/modalButton.module.css
  src/components/buttons/styles/optionButton.module.css
  src/components/buttons/styles/roundButton.module.css
  src/components/buttons/styles/share.module.css
  src/components/buttons/styles/topMenuButton.module.css
  src/components/spalsh.module.css
Labels: STYLE, 이수현

#26 Style: 메뉴판 입력 모달 컴포넌트 작업 완
  src/app/page.tsx
  src/components/modals/InputModal.tsx
  src/components/modals/MenuCardModal.tsx
  src/components/modals/TrialViewModal.tsx
  src/components/modals/styles/inputModal.module.css
  src/components/modals/styles/menuCardModal.module.css
  src/components/modals/styles/trialViewModal.module.css
Labels: STYLE, 정재호

#28 Style: 삭제 알림 모달 컴포넌트 작업 완료
  src/app/page.tsx
  src/components/buttons/styles/topMenuButton.module.css
  src/components/modals/NoticeModal.tsx
  src/components/modals/styles/noticeModal.module.css
Labels: STYLE, 정재호

#30 Style: 더보기 모달 컴포넌트 제작 완료
  public/svg/moreIcon.svg
  src/app/page.tsx
  src/components/modals/MoreModal.tsx
  src/components/modals/styles/moreModal.module.css
  src/components/modals/styles/trialViewModal.module.css
Labels: STYLE, 정재호

#35 Style/TabNavigation
  public/icons/Icon_mypage.svg
  src/app/myMenuBoard/myMenu.module.css
  src/app/myMenuBoard/page.tsx
  src/app/teamMenuBoard/page.tsx
  src/app/teamMenuBoard/teamMenuBoard.module.css
  src/components/Header.tsx
  src/components/TabNavigation.tsx
  src/components/header.module.css
  src/components/tabNav.module.css
Labels: STYLE, 이수현

#37 Style/TopNavBar Component
  public/icons/Icon_back.svg
  src/app/page.tsx
  src/components/TopNavBar.tsx
  src/components/modals/MoreModal.tsx
  src/components/topNavBar.module.css
Labels: STYLE, 이수현

#40 Style: 팀 정보 수정 모달 컴포넌트 작업 완료
  src/app/page.tsx
  src/components/modals/ModifyModal.tsx
  src/components/modals/MoreModal.tsx
  src/components/modals/styles/modifyModal.module.css
  src/components/modals/styles/moreModal.module.css
Labels: STYLE, 정재호

#43 Style: LoginPage Layout
  public/image/kakao_login_medium_wide.png
  public/svg/kakao_login_large_wide.svg
  src/app/login/login.module.css
  src/app/login/page.tsx
  src/components/TopNavBar.tsx
  src/components/buttons/Button.tsx
  src/components/buttons/styles/button.module.css
Labels: STYLE, 이수현

#45 Feat: 카카오 로그인 버튼 눌렀을때 기능 작업 완료
  src/app/login/kakao/page.tsx
  src/app/login/page.tsx
  src/components/modals/MenuCardModal.tsx
  swiper.bundle.css
Labels: STYLE, 정재호, 🚀 FEAT

#48 Chore: useAuthStore.ts 작업 완료
  package-lock.json
  package.json
  src/app/login/store/useAuthStore.ts
Labels: ⚙️ CHORE, 정재호

#50 Style/bottom sheet
  package-lock.json
  package.json
  src/app/home/home.module.css
  src/app/home/page.tsx
  src/components/BottomSheet/BTMHeader.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/bottomSheet.module.css
  src/hooks/useBottomSheet.ts
  src/hooks/usePreviousValue.ts
Labels: STYLE, 이수현

#55 Style/bottom sheet inner components 나의 메뉴판 추가하기
  .prettierrc
  public/icons/checkBox/checkBox_checked.svg
  public/icons/checkBox/checkBox_unchecked.svg
  public/icons/close.svg
  public/icons/down.svg
  public/icons/up.svg
  src/app/home/home.module.css
  src/app/home/page.tsx
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/NoMenu_BS.tsx
  src/components/BottomSheet/addMenu.module.css
  src/components/BottomSheet/bottomSheet.module.css
  src/components/BottomSheet/noMenu.module.css
  src/components/buttons/Button.tsx
  src/components/buttons/OptionButton.tsx
  src/components/buttons/ShareButton.tsx
  src/components/buttons/styles/button.module.css
  src/components/buttons/styles/optionButton.module.css
Labels: STYLE, 이수현

#56 Style: /home 페이지 목록 컴포넌트 작업 중
  public/svg/informationIcon.svg
  src/app/home/_components/InformationModal.tsx
  src/app/home/_components/MenuEmpty.tsx
  src/app/home/_components/MyMenuList.tsx
  src/app/home/_components/TeamMenuList.tsx
  src/app/home/_components/styles/informationModal.module.css
  src/app/home/_components/styles/menuEmpty.module.css
  src/app/home/home.module.css
  src/app/home/page.tsx
  src/data/menuList.ts
Labels: STYLE, 정재호

#58 refactor: Header & DropBox
  public/icons/Icon_mypage.svg
  src/app/home/home.module.css
  src/components/TabNavigation.tsx
  src/components/modals/styles/moreModal.module.css
  src/components/tabNav.module.css
Labels: ♻️ REFACTOR, STYLE, 이수현

#62 style: 초대받은 게스트 화면 퍼블리싱
  src/app/guest_invitation/invitation.module.css
  src/app/guest_invitation/page.tsx
  src/app/login/login.module.css
  src/components/buttons/ModalButton.tsx
  src/components/buttons/styles/modalButton.module.css
  src/components/modals/NoticeModal.tsx
Labels: STYLE, 이수현

#64 Style: 메뉴판 페이지 목록 컴포넌트 작업 완료
  package-lock.json
  package.json
  public/svg/rightArrow.svg
  src/_lib/axios.ts
  src/app/home/_components/MenuEmpty.tsx
  src/app/home/_components/styles/menuEmpty.module.css
  src/app/home/page.tsx
  src/app/makeTeam/page.tsx
  src/components/TopNavBar.tsx
  src/data/menuList.ts
Labels: STYLE, 정재호

#66 import 철자 수정
  src/components/BottomSheet/BTMHeader.tsx
  src/components/BottomSheet/BottomSheet.tsx
Labels: 🐛 BUG, 정재호, 🚨 HOTFIX

#67 Style: 확인 버튼 하나만 있는 alertModal 작업 완료
  public/svg/checkIcon.svg
  src/app/page.tsx
  src/components/modals/AlertModal.tsx
  src/components/modals/styles/alertModal.module.css
Labels: STYLE, 정재호

#69 Style: 마이페이지 퍼블리싱 작업 완료
  src/app/myPage/myPage.module.css
  src/app/myPage/page.tsx
  src/components/Header.tsx
  src/data/menuList.ts
Labels: STYLE, 정재호

#77 Style/creating team menu
  public/icons/Icon_pencil.svg
  public/icons/buttons/Icon_refresh.svg
  public/svg/Icon_copyURL.svg
  public/svg/Icon_kakao.svg
  src/app/login/login.module.css
  src/app/makeTeam/page.tsx
  src/app/teamMenuPage/page.tsx
  src/app/teamMenuPage/teamMenu.module.css
  src/app/vote/page.tsx
  src/app/vote/vote.module.css
  src/app/vote/voteResult/components/voteResultCard.module.css
  src/app/vote/voteResult/components/voteResultCard.tsx
  src/app/vote/voteResult/page.tsx
  src/app/vote/voteResult/voteResult.module.css
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/InputBox/input.module.css
  src/components/buttons/RoundButton.tsx
  src/components/buttons/styles/roundButton.module.css
  src/components/menuItem/myMenuItem.module.css
  src/components/menuItem/teamMenuItem.module.css
  src/components/spalsh.module.css
  src/components/topNavBar.module.css
  src/hooks/useBottomSheet.ts
Labels: STYLE, 이수현

#79 Style/menu board
  public/icons/food_category/멕시코.svg
  public/icons/food_category/멕시코_gray.svg
  public/icons/food_category/양식.svg
  public/icons/food_category/양식_gray.svg
  public/icons/food_category/육해.svg
  public/icons/food_category/육해_gray.svg
  public/icons/food_category/인태베.svg
  public/icons/food_category/인태베_gray.svg
  public/icons/food_category/일식.svg
  public/icons/food_category/일식_gray.svg
  public/icons/food_category/중식.svg
  public/icons/food_category/중식_gray.svg
  public/icons/food_category/한식.svg
  public/icons/food_category/한식_gray.svg
  public/svg/square.svg
  src/app/menu/menu.module.css
  src/app/menu/page.tsx
  src/app/vote/components/voteDone.tsx
  src/app/vote/voteResult/page.tsx
  src/components/MenuBoard/MenuBoard.tsx
  src/components/MenuBoard/menuBoard.module.css
  src/components/TopNavBar.tsx
  src/components/buttons/ShareButton.tsx
  src/components/buttons/TopMenuButton.tsx
  src/components/buttons/styles/button.module.css
  src/types/IMenu.d.ts
Labels: STYLE, 이수현

#84 Style: Loading 컴포넌트 추가
  public/svg/orangeBackgroundLoading.svg
  public/svg/whiteBackgroundLoading.svg
  src/app/menu/page.tsx
  src/components/BottomSheet/AddTaste_BS.tsx
  src/components/Loading.tsx
  src/components/buttons/styles/button.module.css
  src/components/loading.module.css
Labels: STYLE, 정재호

#86 Deploy: build 오류 수정
  src/app/home/_components/MyMenuList.tsx
  src/components/menuItem/MyMenuItem.tsx
Labels: DEPLOY, 정재호, 🛠️ FIX

#88 Feat: 이미지 저장 기능 구현 완료
  package-lock.json
  package.json
  src/app/menu/menu.module.css
  src/app/menu/page.tsx
  src/app/teamMenuPage/page.tsx
  src/app/teamMenuPage/teamMenu.module.css
  src/app/vote/voteResult/voteResult.module.css
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/MenuBoard/menuBoard.module.css
  src/components/buttons/ShareButton.tsx
Labels: 정재호, 🚀 FEAT

#89 feat: 링크 복사하기
  src/app/teamMenuPage/page.tsx
  src/app/teamMenuPage/teamMenu.module.css
Labels: 이수현, 🚀 FEAT

#92 Fix/login url/jh
  src/app/teamMenuPage/page.tsx
Labels: 정재호, 🚨 HOTFIX

#93 refactor: ui 수정
  src/app/home/_components/MyMenuList.tsx
  src/components/BottomSheet/addMenu.module.css
  src/components/BottomSheet/addTaste.module.css
  src/components/BottomSheet/bottomSheet.module.css
Labels: ♻️ REFACTOR, STYLE, 이수현

#95 Feat: axios 인터셉터 추가, home 페이지 처음 렌더링 될때 accessToken 받아오는 코드 주석표시
  src/_lib/axios.ts
  src/api/postRefresh.ts
  src/app/home/_components/MyMenuList.tsx
  src/app/home/_components/TeamMenuList.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/login/store/useAuthStore.ts
  src/components/menuItem/MyMenuItem.tsx
  src/components/menuItem/TeamMenuItem.tsx
Labels: 정재호, 🚀 FEAT

#97 Feat: 로그아웃 api 연동 작업 완료
  src/api/postLogout.ts
  src/app/guest_invitation/invitation.module.css
  src/app/guest_invitation/page.tsx
  src/app/myPage/page.tsx
  src/components/modals/NoticeModal.tsx
Labels: STYLE, 정재호, 🚀 FEAT, 🛠️ FIX

#98 Chore: favicon 이미지 설정
  src/app/layout.tsx
Labels: ⚙️ CHORE, 정재호

#100 feat: 카카오맵 검색기능
  package-lock.json
  package.json
  public/icons/Icon_search.svg
  public/icons/kakaoMap/Icon_marker.svg
  public/icons/kakaoMap/Icon_marker_current.svg
  public/icons/kakaoMap/Icon_marker_selected.svg
  src/_lib/apiRoutes.ts
  src/app/home/page.tsx
  src/app/home/store/useHomeStore.ts
  src/app/kakaoMap/components/Kakao_Map.tsx
  src/app/kakaoMap/components/map.module.css
  src/app/kakaoMap/kakaoMap.module.css
  src/app/kakaoMap/page.tsx
  src/app/layout.tsx
  src/components/TabNavigation.tsx
  src/hooks/useKakaoLoader.ts
  src/types/IGetTemMenu.d.ts
  src/utils/constant.ts
Labels: STYLE, 이수현, 🚀 FEAT

#101 Fix/UI
  src/_lib/axios.ts
  src/app/home/_components/styles/informationModal.module.css
  src/app/home/page.tsx
  src/components/tabNav.module.css
Labels: STYLE, 이수현, 🛠️ FIX

#102 Feat: 나의 메뉴판 생성할떄 기본값으로 'OOO의 메뉴판' 설정 및 나의 메뉴판 생성 api 연동 작업 완료
  src/_lib/apiRoutes.ts
  src/_lib/axios.ts
  src/api/getMyMenuList.ts
  src/api/getTeamMenuList.ts
  src/api/postCreateMyMenu.ts
  src/app/createMyMenu/page.tsx
  src/app/home/_components/MyMenuList.tsx
  src/app/home/_components/TeamMenuList.tsx
  src/app/home/home.module.css
  src/app/home/page.tsx
  src/app/home/store/useHomeStore.ts
  src/app/kakaoMap/components/Kakao_Map.tsx
  src/components/BottomSheet/AddTaste_BS.tsx
  src/types/IGetMyMenu.d.ts
  src/utils/constant.ts
Labels: 정재호, 🚀 FEAT, 🛠️ FIX

#106 fix: axios 삭제, fetcher 파일 생성, api 호출 파일 수정
  package-lock.json
  package.json
  src/_lib/axios.ts
  src/_lib/fetcher.ts
  src/_lib/refreshTokenExpired.ts
  src/api/getMyMenuList.ts
  src/api/getTeamMenuList.ts
  src/api/getUserName.ts
  src/api/postCreateMyMenu.ts
  src/api/postLogout.ts
  src/api/postRefresh.ts
  src/app/home/page.tsx
  src/app/login/store/useAuthStore.ts
Labels: 정재호, 🛠️ FIX, 🚨 HOTFIX

#107 feat: 나의 메뉴판 api 연동 작업중
  src/api/deleteMyMenu.ts
  src/api/patchModifyMyMenu.ts
  src/app/createMyMenu/page.tsx
  src/app/home/_components/MyMenuList.tsx
  src/app/home/home.module.css
  src/app/home/page.tsx
  src/app/kakaoMap/components/Kakao_Map.tsx
  src/app/login/store/useAuthStore.ts
  src/components/BottomSheet/BottomSheet.tsx
  src/components/InputBox/SmallInput.tsx
  src/components/TopNavBar.tsx
  src/components/buttons/ModalButton.tsx
  src/components/menuItem/MyMenuItem.tsx
  src/components/modals/AlertModal.tsx
  src/components/modals/InputModal.tsx
  src/components/modals/MenuCardModal.tsx
  src/components/modals/ModifyModal.tsx
  src/components/modals/MoreModal.tsx
  src/components/modals/NoticeModal.tsx
  src/components/modals/TrialViewModal.tsx
  src/types/IPatchMyMenuName.d.ts
Labels: 정재호, 🚀 FEAT, 🛠️ FIX

#108 feat: 나의 매뉴판 api 연동 작업중
  src/api/getMyMenu.ts
  src/api/postRecommendMyMenu.ts
  src/app/createMyMenu/page.tsx
  src/app/home/_components/MyMenuList.tsx
  src/app/home/home.module.css
  src/app/home/page.tsx
  src/app/menu/menu.module.css
  src/app/menu/page.tsx
  src/components/BottomSheet/AddTaste_BS.tsx
  src/components/MenuBoard/MenuBoard.tsx
  src/components/TopNavBar.tsx
  src/components/modals/InputModal.tsx
  src/components/modals/NoticeModal.tsx
  src/data/Categories.ts
  src/types/ICategory.d.ts
  src/types/IGetMyMenu.d.ts
Labels: 정재호, 🚀 FEAT

#110 Feat: menuBoard에서 menuItemModal api 연동 작업 완료
  next.config.mjs
  package-lock.json
  package.json
  src/_lib/axios.ts
  src/api/patchModifyMyMenu.ts
  src/app/createMyMenu/page.tsx
  src/app/layout.tsx
  src/app/menu/page.tsx
  src/app/myPage/page.tsx
  src/app/page.tsx
  src/app/trial_version/page.tsx
  src/components/BottomSheet/AddTaste_BS.tsx
  src/components/MenuBoard/MenuBoard.tsx
  src/components/buttons/ShareButton.tsx
  src/components/modals/InputModal.tsx
  src/components/modals/MenuCardModal.tsx
  src/data/Categories.ts
Labels: 정재호, 🚀 FEAT

#111 fix: 배포 오류 수정
  src/app/menu/page.tsx
  src/app/teamMenuPage/page.tsx
  src/app/trial_version/page.tsx
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/modals/NoticeModal.tsx
Labels: DEPLOY, 정재호

#112 fix: home 페이지 코드 수정
  src/app/home/page.tsx
Labels: DEPLOY, 정재호, 🛠️ FIX

#113 chore: 배포사이트에서 확인하기 위한 console 추가
  src/api/postRefresh.ts
  src/app/home/page.tsx
Labels: ⚙️ CHORE, 정재호

#114 fix: refresh 관련 수정
  src/_lib/fetcher.ts
  src/_lib/refreshTokenExpired.ts
  src/api/postRefresh.ts
  src/app/home/home.module.css
  src/app/home/page.tsx
Labels: DEPLOY, 정재호, 🛠️ FIX

#115 build 에러 수정
  src/api/postRefresh.ts
Labels: 🐛 BUG, 정재호, 🚨 HOTFIX

#116 fix: 빌드 에러 수정
  src/api/postRefresh.ts
  src/app/home/page.tsx
Labels: 🐛 BUG, 정재호, 🚨 HOTFIX

#117 fix: refresh api 수정에 따른 응답 데이터 사용 코드 수정
  src/_lib/fetcher.ts
  src/api/postRefresh.ts
  src/app/home/page.tsx
Labels: 정재호, 🛠️ FIX

#118 refactor: 더보기 모달 수정 & 팀 메뉴판 수정 기능
  src/api/patchModifyTeamMenu.ts
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/modals/InputModal.tsx
  src/components/modals/ModifyModal.tsx
  src/components/modals/MoreModal.tsx
Labels: ♻️ REFACTOR, 이수현, 🚀 FEAT

#125 styles:마이페이지 지난 투표결과 추가
  public/icons/buttons/rignt.svg
  src/app/myPage/myPage.module.css
  src/app/myPage/page.tsx
  src/app/vote/components/voteDone.tsx
  src/app/vote/components/voting.tsx
  src/app/vote/voteResult/components/voteResultCard.module.css
  src/app/vote/voteResult/components/voteResultCard.tsx
  src/app/vote/voteResult/page.tsx
  src/components/modals/NoticeModal.tsx
Labels: STYLE, 이수현

#126 Feat: 체험판 페이지 api 연동 작업 완료 및 투표 제한 로직 수정
  src/_lib/apiRoutes.ts
  src/api/postGuestRecommend.ts
  src/api/postRefresh.ts
  src/app/home/_components/MenuEmpty.tsx
  src/app/home/page.tsx
  src/app/menu/page.tsx
  src/app/teamMenuPage/page.tsx
  src/app/trial_version/page.tsx
  src/app/vote/components/voting.tsx
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/BottomSheet/AddTaste_BS.tsx
  src/components/InputBox/SmallInput.tsx
  src/components/TabNavigation.tsx
  src/components/TopNavBar.tsx
  src/components/modals/AlertModal.tsx
  src/components/modals/InputModal.tsx
  src/components/modals/MoreModal.tsx
  src/components/modals/NoticeModal.tsx
  src/components/modals/TrialViewModal.tsx
Labels: 정재호, 🚀 FEAT, 🛠️ FIX

#127 fix: isMoreModal
  src/app/home/_components/TeamMenuList.tsx
  src/components/TopNavBar.tsx
  src/components/menuItem/TeamMenuItem.tsx
  src/components/modals/InputModal.tsx
  src/components/modals/ModifyModal.tsx
  src/components/modals/MoreModal.tsx
  src/components/modals/NoticeModal.tsx
Labels: 이수현, 🛠️ FIX

#128 fix/더보기 모달
  src/app/home/_components/TeamMenuList.tsx
  src/components/TopNavBar.tsx
  src/components/menuItem/TeamMenuItem.tsx
Labels: 이수현, 🛠️ FIX

#131 Refactor: 더보기 모달 레이아웃 오류 수정(팀메뉴판, 나의 메뉴판 모두)
  robots.txt
  src/app/home/_components/MyMenuList.tsx
  src/app/home/_components/TeamMenuList.tsx
  src/app/home/_components/styles/menuList.module.css
  src/app/vote/components/voteComponents.module.css
  src/components/TopNavBar.tsx
  src/components/menuItem/MyMenuItem.tsx
  src/components/menuItem/TeamMenuItem.tsx
  src/components/menuItem/teamMenuItem.module.css
Labels: ♻️ REFACTOR, STYLE, 정재호

#134 Refactor: selectbox 레이아웃 오류 수정(styles.ul sticky를 absolte로 수정)
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/BottomSheet/addMenu.module.css
Labels: ♻️ REFACTOR, STYLE, 정재호

#135 Feat: 마이페이지, voteResult 페이지 api 연동작업 완료
  src/_lib/apiRoutes.ts
  src/api/getMyPageInfo.ts
  src/api/getMyPageVotes.ts
  src/app/home/_components/MyMenuList.tsx
  src/app/home/page.tsx
  src/app/menu/page.tsx
  src/app/myPage/myPage.module.css
  src/app/myPage/page.tsx
  src/app/vote/voteResult/components/voteResultCard.tsx
  src/app/vote/voteResult/page.tsx
  src/app/vote/voteResult/voteResult.module.css
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/BottomSheet/AddTaste_BS.tsx
  src/components/TabNavigation.tsx
  src/components/menuItem/MyMenuItem.tsx
  src/components/menuItem/TeamMenuItem.tsx
  src/components/modals/MoreModal.tsx
  src/types/IGetMyPage.d.ts
Labels: 정재호, 🚀 FEAT

#138 배경 이미지 삽입
  public/svg/backgroundImg.svg
  src/app/layout.tsx
  src/app/styles/globals.css
Labels: STYLE, 정재호

#139 Feat: 카카오로 메뉴판 링크 공유하기 수정중 스위그 배포를 위한 pr
  package-lock.json
  package.json
  public/image/openGraphImg.png
  src/_lib/apiRoutes.ts
  src/api/uploadImageToS3.ts
  src/app/layout.tsx
  src/app/menu/page.tsx
  src/app/shareImage/page.tsx
  src/app/styles/globals.css
  src/components/TabNavigation.tsx
  src/components/TopNavBar.tsx
  src/components/modals/MoreModal.tsx
  src/hooks/useKakaoShare.ts
  src/types/KakaoType.d.ts
Labels: DEPLOY, 정재호, 🚀 FEAT

#140 deploy: 메타 데이터 수정
  public/image/감자탕.jpg
  src/app/layout.tsx
  src/types/MetaData.d.ts
Labels: DEPLOY, 정재호

#141 deploy: metadataBase 스위그 도메인 링크 추가
  src/app/layout.tsx
  src/types/MetaData.d.ts
Labels: DEPLOY, 정재호

#142 Refactor: 팀 정보 수정 모달 수정 작업 완료 및 qa 오류 수정
  src/app/home/_components/TeamMenuList.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/login/_components/TutorialStep.tsx
  src/app/makeTeam/page.tsx
  src/components/TopNavBar.tsx
  src/components/modals/ModifyModal.tsx
  src/components/modals/styles/modifyModal.module.css
Labels: ♻️ REFACTOR, 정재호

#143 Feat: 카카오 공유하기 메뉴판 이미지만 있는 페이지 링크 공유 작업 완료
  src/api/uploadImageToS3.ts
  src/app/home/page.tsx
  src/app/kakaoMap/components/Kakao_Map.tsx
  src/app/kakaoMap/kakaoMap.module.css
  src/app/kakaoMap/page.tsx
  src/app/layout.tsx
  src/app/menu/page.tsx
  src/app/page.tsx
  src/app/shareImage/page.tsx
  src/app/shareImage/shareImage.module.css
  src/components/TabNavigation.tsx
  src/components/TopNavBar.tsx
  src/components/modals/TrialViewModal.tsx
  src/hooks/useKakaoShare.ts
  src/utils/KakaoInitializer.ts
Labels: 정재호, 🚀 FEAT

#145 feat: 팀 메뉴판에서 카카오톡 팀원 초대하기 기능 완료
  public/image/openGraphImg.png
  src/app/layout.tsx
  src/app/teamMenuPage/page.tsx
  src/app/vote/components/voting.tsx
  src/components/modals/InviteModal.tsx
  src/components/modals/ModifyModal.tsx
  src/components/modals/MoreModal.tsx
  src/components/modals/styles/inviteModal.module.css
  src/components/modals/styles/modifyModal.module.css
  src/hooks/useKakaoInvite.ts
  src/hooks/useKakaoShare.ts
Labels: 정재호, 🚀 FEAT

#147 fix: 체험판 페이지에서 처음에 입력란엔 placeholder만 있고 말풍선이 나오도록 수정 완료
  src/app/menu/page.tsx
  src/app/trial_version/page.tsx
  src/components/TopNavBar.tsx
Labels: STYLE, 정재호, 🛠️ FIX

#149 Fix: 바텀시트 setIsOpen 수정(useBottomSheet훅을 zustand 전역상태변수로 수정)
  src/app/createMyMenu/page.tsx
  src/app/guest_invitation/page.tsx
  src/app/home/page.tsx
  src/app/menu/page.tsx
  src/app/teamMenuPage/page.tsx
  src/app/trial_version/page.tsx
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/BottomSheet/AddTaste_BS.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/MenuBoard/MenuBoard.tsx
  src/components/MenuBoard/menuBoard.module.css
  src/components/TopNavBar.tsx
  src/hooks/useBottomSheet.ts
Labels: 정재호, 🛠️ FIX

#150 카카오 공유할때 제목, 설명글 수정
  src/hooks/useKakaoInvite.ts
  src/hooks/useKakaoShare.ts
Labels: 정재호, 🛠️ FIX

#151 fix: 체험판 바텀시트 setIsOpen 조건 추가
  src/app/trial_version/page.tsx
Labels: 정재호, 🛠️ FIX

#152 refactor: 로그인상태일때만 메뉴판 페이지 api 호출하는 것으로 수정
  package.json
  src/app/menu/page.tsx
  src/components/BottomSheet/AddTaste_BS.tsx
Labels: ♻️ REFACTOR, 정재호

#154 refactor: 로그인 여부에 따라 menu 페이지 api 호출 방법 다르게 수정
  src/app/menu/page.tsx
Labels: 🐛 BUG, ♻️ REFACTOR, 정재호

#156 Feat/vote
  src/api/getVoteMembers.ts
  src/api/getVoteResult.ts
  src/api/patchEditVote.ts
  src/app/menu/page.tsx
  src/app/myPage/page.tsx
  src/app/vote/components/voteComponents.module.css
  src/app/vote/components/voteDone.tsx
  src/app/vote/components/voteResult.tsx
  src/app/vote/components/voting.tsx
  src/app/vote/page.tsx
  src/app/vote/voteResult/components/voteResultCard.module.css
  src/components/TopNavBar.tsx
  src/types/IGetVote.d.ts
Labels: 이수현, 🚀 FEAT, 🛠️ FIX

#157 Feat: 팀원 초대 api 연동작업 완료 + 기타 등등
  src/_lib/apiRoutes.ts
  src/api/postInvite.ts
  src/app/guest_invitation/page.tsx
  src/app/myPage/myPage.module.css
  src/app/teamMenuPage/page.tsx
  src/types/IPostInvite.d.ts
Labels: ♻️ REFACTOR, 정재호, 🚀 FEAT

#160 fix: 바텀시트 옵션 적용 버튼 Ui
  src/components/BottomSheet/AddTaste_BS.tsx
  src/components/BottomSheet/addMenu.module.css
  src/components/BottomSheet/addTaste.module.css
Labels: STYLE, 이수현, 🛠️ FIX

#161 fix: isAllpeopleAdded
  src/components/menuItem/TeamMenuItem.tsx
Labels: STYLE, 이수현, 🛠️ FIX

#163 Feat: 팀 메뉴판 페이지 수정 api 연동 작업 완료 & 팀 메뉴판에서페이지에서 새로고침하면 메뉴 안받아와지는 에러 해결
  src/api/patchTeamMenus.ts
  src/app/menu/page.tsx
  src/app/teamMenuPage/page.tsx
  src/components/BottomSheet/AddMenu_BS.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/menuItem/TeamMenuItem.tsx
Labels: 정재호, 🚀 FEAT, 🛠️ FIX

#165 feat: 팀메뉴판에서 팀원인지 아닌지 구분해주는 api 연동작업 완료
  src/api/getInvite.ts
  src/app/teamMenuPage/page.tsx
  src/types/IGetInvite.d.ts
Labels: 정재호, 🚀 FEAT

#166 fix: 로그인 페이지, 게스트 초대 페이지 두페이지에 대한 로그인 리디렉션 home, 게스트 초대 페이지 설정 수정
  src/app/guest_invitation/page.tsx
  src/app/home/page.tsx
Labels: 정재호, 🛠️ FIX

#167 Fix: 팀메뉴판 관련 에러 수정 및 바텀 add_Menu 바텀시트 스타일 조정
  src/app/home/_components/TeamMenuList.tsx
  src/app/teamMenuPage/page.tsx
  src/app/vote/components/voteDone.tsx
  src/components/BottomSheet/addMenu.module.css
  src/types/IGetTemMenu.d.ts
Labels: STYLE, 정재호, 🛠️ FIX

#168 Fix: 게스트 초대 페이지에서 수락버튼 눌렀을때 리디렉션 오류 나던 부분 수정 완료 등등
  src/api/getHasMenuAddedMembers.ts
  src/api/getInvite.ts
  src/api/getTeamMenuItem.ts
  src/app/guest_invitation/page.tsx
  src/app/teamMenuPage/page.tsx
  src/app/vote/components/voteResult.tsx
  src/app/vote/page.tsx
  src/components/menuItem/TeamMenuItem.tsx
  src/hooks/useKakaoShare.ts
  src/types/IPostInvite.d.ts
Labels: 정재호, 🚀 FEAT, 🛠️ FIX

#169 fix: 팀 메뉴판에서 유저가 메뉴 추가해도 querykey 무효화하지 않던 에러 수정
  src/app/teamMenuPage/page.tsx
  src/components/BottomSheet/AddMenu_BS.tsx
Labels: 정재호, 🛠️ FIX
